FROM python:3.12-slim

WORKDIR /app

# Copier le code nécessaire
COPY app.py database.py requirements.txt ./
COPY templates ./templates
COPY static ./static

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Lancer Flask
CMD ["python", "app.py"]
